version: 1
timeout: "1m"
cache:
  type: 'SQLite'

validators: 
  - regex: '(^http[s]?:\/\/)(www\.)?(github\.com\/)coralogix\/telemetry-shippers(\/pull\/|\/issues\/)'
    type: 'githubPullsIssues'
  # Ignore links that includes 'assets' because the generated content will resolve them correctly.
  - regex: '.+/a/.+'
    type: ignore
