version: 1
timeout: "1m"
cache:
  type: 'SQLite'

validators: 
  - regex: 'issue'
    type: 'githubPullsIssues'
  # Ignore links that includes 'assets' because the generated content will resolve them correctly.
  - regex: '.+/a/.+'
    type: ignore
