version: 1
timeout: "1m"
cache:
  type: 'SQLite'

validators: 
  - regex: 'https://github.com/coralogix/telemetry-shippers/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22'
    type: 'ignore'
  # Ignore links that includes 'assets' because the generated content will resolve them correctly.
  - regex: '.+/a/.+'
    type: ignore
