version: 1
timeout: "1m"
cache:
  type: 'SQLite'

validators: 
  - regex: '(^http[s]?:\/\/)(www\.)?(github\.com\/)bwplotka\/mdox(\/pull\/|\/issues\/)'
    type: ignore
  # Ignore links that includes 'assets' because the generated content will resolve them correctly.
  - regex: '.+/a/.+'
    type: ignore
